### ISSUE TITLE
"Release date" rule not working

### ISSUE THREAD

**Issue by joebanana** [Shpigford/plylst#104]
I'm trying to create a playlist out of songs I've liked, based on release date (ie between 2019 Jan 1st and 2019 Dec 31).

No songs are returned, although I do have songs that were release that year.

**Comment by joebanana** [comment]
Nevermind, it seems it's just not "live". When the playlists refresh, I can see their contents. I wish I could refresh whenever I want though :)

**Comment by Shpigford** [comment]
Hey Joe! Yeah, there's a bit of caching that happens. Depending on current server load it can take anywhere from a few minutes to an hour or so.

**Comment by joebanana** [comment]
I realized that by editing and saving the playlist, the refresh is
immediate, which very well suits my needs. This is brilliant, thank
you so much for this :)

2020-09-02 13:03 UTC−04:00, Josh Pigford <notifications@github.com>:
