### ISSUE TITLE
[Feature Request] Smart Playlist referring other playlist / ability for rules: match --> any, all

### ISSUE THREAD

**Issue by jaddel** [Shpigford/plylst#105]
It would be nice to build playlists based on other playlists like in the screenshot below.

<img width="621" alt="Screenshot 2020-08-29 at 14 26 38" src="https://user-images.githubusercontent.com/46263124/91636805-a9a22a00-ea03-11ea-80ad-27eb41fca80e.png">

**Comment by oligriffiths** [comment]
yes I also want to do this. I want to use a source playlist and filter it down to songs longer than 5 minutes.
