### ISSUE TITLE
Dependency to mimemagic 0.3.5 shound't be used anymore

### ISSUE THREAD

**Issue by Evanaellio** [Shpigford/plylst#112]
Running `bundle install` gives the following error with regards to mimemagic :

```
Your bundle is locked to mimemagic (0.3.5), but that version could not be found
in any of the sources listed in your Gemfile. If you haven't changed sources,
that means the author of mimemagic (0.3.5) has removed it. You'll need to update
your bundle to a version other than mimemagic (0.3.5) that hasn't been removed
in order to install.
```

The dependency [mimeagic 0.3.5](https://rubygems.org/gems/mimemagic/versions/0.3.5) was deleted because of licensing issues and shouldn't be used anymore.

**Comment by merchizm** [comment]
I fixed this problem with this command,
"bundle update mimemagic"

**Comment by Evanaellio** [comment]
Fixed with https://github.com/Shpigford/plylst/commit/fc964ab837c3d69930b3c5ce709401f30b78a942
