### ISSUE TITLE
Creating playlist with a play count possibly breaks the playlist page

### ISSUE THREAD

**Issue by forby** [Shpigford/plylst#13]
Love the idea so far but I'm running into an issue where each of my playlists are broken in the app. Not sure if there are other factors, but it seems to happen consistently when I create a new playlist with:

- a genre
- a play count
- a play count filter of "greater than"

Now I have three playlists that all return "We're sorry, but something went wrong." when I try to access them. Maybe this also happens for other rulesets but I haven't tested them all.

**Comment by Shpigford** [comment]
Just pushed a fix for it. Can you give it a try again?

**Comment by forby** [comment]
That fixed it for 2 out of 3 of them! So close.

**Comment by forby** [comment]
I'll add though that for the one that's still broken, I had made that yesterday and I'm pretty sure it had several other rules set. But I don't remember which ones.

**Comment by Shpigford** [comment]
Ah, missed one spot in the code for that other one. Give it a go now!

**Comment by forby** [comment]
Boom! That fixed it. You're on it man 🏆
