### ISSUE TITLE
Create a "rule builder"

### ISSUE THREAD

**Issue by Shpigford** [Shpigford/plylst#3]
<img width="944" alt="Screen Shot 2019-06-17 at 10 35 24 AM" src="https://user-images.githubusercontent.com/35243/59617308-b632af00-90eb-11e9-9a74-7354bb16462c.png">

This will only get more ridiculous as more rules are added. We really need a "rule builder" where you add rules one at a time instead of seeing the whole dang form.

Will require a decent amount of javascript and that's, unfortunately, not my strong suit. Would love some help on this!

**Comment by jamespember** [comment]
See issues #6 and #7 too.
