### ISSUE TITLE
Option to make playlists private when generating

### ISSUE THREAD

**Issue by forby** [Shpigford/plylst#33]
I just noticed that all of my generated playlists are public and need to be manually changed to private. It would be helpful to either have a toggle for private when creating. Or maybe a global default setting so all future playlists can be private unless changed? Might be cool.

**Comment by brianroach** [comment]
+1 for this. 😁

**Comment by Shpigford** [comment]
Great idea!

**Comment by Shpigford** [comment]
Just rolled this out! You'll now find an option to make the playlist private when creating/editing.

Thanks for the suggestion!
