### ISSUE TITLE
Combine "build a new playlist" and "edit playlist" screens

### ISSUE THREAD

**Issue by holic** [Shpigford/plylst#46]
I've used plylst sparingly, just checking in every once in a while to see how the project is progressing. Something that always gets me stuck is having to a name a playlist before I've had a chance to explore the options for creating a playlist.

Since the playlist name is editable from the second screen, maybe we can just remove the first screen and give it a preset name like "Untitled playlist" or something? That'd get folks quicker to the playlist builder screen.

**Comment by Shpigford** [comment]
@holic Great idea! Smashed 'em together. :)

**Comment by holic** [comment]
👏  So fast! Thanks!
