### ISSUE TITLE
Deleting a Playlist in Plylst should delete the playlist in Spotify

### ISSUE THREAD

**Issue by jamespember** [Shpigford/plylst#5]

**Comment by Shpigford** [comment]
Unfortunately not possible. Spotify doesn't provide an endpoint for deleting a playlist.

https://developer.spotify.com/documentation/general/guides/working-with-playlists/#following-and-unfollowing-a-playlist

> We have no endpoint for deleting a playlist in the Web API; the notion of deleting a playlist is not relevant within the Spotify’s playlist system. Even if you are the playlist’s owner and you choose to manually remove it from your own list of playlists, you are simply unfollowing it. Although this behavior may sound strange, it means that other users who are already following the playlist can keep enjoying it.

**Comment by jamespember** [comment]
Ah bummer!
