### ISSUE TITLE
Selecting genre doesn't select entire artists catalog

### ISSUE THREAD

**Issue by forby** [Shpigford/plylst#52]
Maybe I'm thinking about this wrong, but after creating a playlist with a specific genre I'd expect for all of the songs from an artist of that genre to be included. Instead, only a subset of the artist's songs are included (a few from each album).

From what I could tell, genres are applied to the artist and not the tracks themselves. How do I get a genre-based playlist to include an entire artist (or even album) from that genre?

**Comment by Shpigford** [comment]
Depends on sorting. Can you give me an example? Or let me know your exact settings for the whole playlist and I'll see if I can duplicate?

**Comment by forby** [comment]
Hmm, I'm noticing that the discrepancy is dependent on if the songs are _liked_ or not. I guess I was thinking the **On My Library** setting would choose anything I had in a playlist, but this only chooses from songs I've liked?

**Comment by Shpigford** [comment]
@forby Ah, yes. "On My Library" means "Liked". Don't have a way to pull from playlists directly just yet.

**Comment by forby** [comment]
Ah! That clears it up, thanks!
