### ISSUE TITLE
Save tracks performance

### ISSUE THREAD

**Issue by kc-beard** [Shpigford/plylst#53]
SaveTracksWorker is a highly used process (5.5k/hr) using alot of bandwidth (9.7s/job). I think uniqueness constraints in rails are biting us here. 

[Here](https://github.com/Shpigford/plylst/blob/master/app/workers/save_tracks_worker.rb#L80) is the beginning of the block in question that lasts ~10s for most jobs. This begins a transaction (3s), attempts to create a follow (3s), then rolls back in 97% of cases (3s). 

I think the rollback is occurring because of the [uniqueness constraint](https://github.com/Shpigford/plylst/blob/6da8d443930df893578b263b60f8e26a55fc87b2/app/models/follow.rb#L6). Rather than offloading that uniqueness to postgres, rails does many queries to validate it in app land, but doesn't actually delegate that uniqueness to the database ([source](https://guides.rubyonrails.org/active_record_validations.html#uniqueness)).

The actual insert, when it does succeed, takes 800ms. I'd be interested to see what performance looks like when relying on a postgres uniqueness contraint vs. the rails constraint.

**Comment by ajjahn** [comment]
The uniqueness validation is happening [here](https://github.com/Shpigford/plylst/blob/master/app/workers/save_tracks_worker.rb#L105) as well.

**Comment by Shpigford** [comment]
Merged @ajjahn's PR. Will let it run a bit and see if it improves things.

**Comment by Shpigford** [comment]
Closing for now. After a number of DB optimizations and implementing some bulk inserts, performance on this worker isn't all that problematic.
