### ISSUE TITLE
How to build playlist based on multiple artists?

### ISSUE THREAD

**Issue by nickdos** [Shpigford/plylst#59]
This is one feature I use in use iTunes **a lot.** 

![image](https://user-images.githubusercontent.com/532845/74072950-b86fc200-4a5c-11ea-81f7-df268dcb2098.png)

Plylst doesn't appear to allow this, although I'm happy to be proven wrong.

#42 is one possible approach. Another is to allow some sort of simplified regex option so artists can be pipe separated in a single rule:

artist -- contains -- artist x|artist y|artist z

Thanks for considering.

**Comment by Shpigford** [comment]
@nickdos The pipe works! Exactly as you've got it in your example. 🙂

If that's not having the results you expect, let me know.

**Comment by nickdos** [comment]
Ha ha - only thought of pipe as I was writing the issue, as an afterthought. 

Seems to work as expected ✅
