### ISSUE TITLE
Add multiple rules based on same variable 

### ISSUE THREAD

**Issue by jamespember** [Shpigford/plylst#6]
For example. I want tracks that are: 

Danceability: Very
  OR 
Danceability: Super

This would also mean adding support for Operators (and / or) for each variable. (#7)

**Comment by Shpigford** [comment]
@jamespember Can you give a few more examples where this would be useful? It'd require a pretty significant overhaul to the way the search queries are built, so want to understand what scenarios it'd actually be used.

**Comment by jackmcdade** [comment]
I'd love this too. I'm trying to generate a running playlist that's right around 170bpm. I can specify greater than 169 or less than 171, but will still get a wildly varied playlist because i can only cap it on one side.

**Comment by jamespember** [comment]
Agree. The “between case” is a good example. “I went between 150 and 190 bpm.”

Another is: I went tracks that are either either heavy metal or hard rock.

Does that make sense? I can also take a look at how you could refactor the rule builder and search queries.

James Pember
076-0264007


________________________________

**Comment by Shpigford** [comment]
So, "between" is actually pretty easy as opposed to an open-ended "multiple".

Right now a broad "add multiples of the same variable" I think adds too much complexity on both the backend side and on the UX side.

Specific use cases on each variable is more tenable. For now going to close this and add a separate ticket for adding "between" to BPM.

**Comment by Shpigford** [comment]
@jackmcdade Just rolled out the "between" operator for BPM!

**Comment by jamespember** [comment]
Awesome! Agree with your view - too much complexity for now.

James Pember
076-0264007


________________________________
