### ISSUE TITLE
Add "Not in Library" filter

### ISSUE THREAD

**Issue by maxnowack** [Shpigford/plylst#61]
Hey, thanks a lot for your great work on this project! 🙂 
I'm trying to create a playlist with all the songs I have listened to at least 3 times, but they are not in my library.
I haven't found a filter for "in library". Am I missing something or is it not implemented yet?

**Comment by Shpigford** [comment]
@maxnowack When you say "In Library" what do you mean? The basis for the songs we pull in are from songs you've "Liked".

Then, you'd just select "Only my library" as the source.

<img width="456" alt="CleanShot 2020-02-18 at 09 35 16@2x" src="https://user-images.githubusercontent.com/35243/74750851-04c3ba80-5232-11ea-9ab1-5721683d9c1d.png">

**Comment by maxnowack** [comment]
@Shpigford yes, but I want to select all the songs I've listened at least three times, but only the songs, which are not in my library. I think that's currently not possible, because I need "All songs" as the source, but want to exclude the songs in my library.

**Comment by Shpigford** [comment]
@maxnowack Ah! Gotcha. You want a "Not in Library" filter. Will add that to the list. Have also updated the ticket title.

**Comment by maxnowack** [comment]
@Shpigford can you give me a hint how this feature could theoretically be implemented? I want to try it by myself 🙂

**Comment by Shpigford** [comment]
@maxnowack Sure! Check the [filtered_tracks](https://github.com/Shpigford/plylst/blob/master/app/models/playlist.rb#L20) method.

Those first few lines ultimately pick where songs come from.

What you're wanting to start with is basically selecting all tracks where `follows.active` is NOT true (as well as where there's no `follows.active` present).

Then you can edit the form dropdown in the [_form.html.erb file](https://github.com/Shpigford/plylst/blob/master/app/views/playlists/_form.html.erb#L30).
