### ISSUE TITLE
Rules doesn't work properly in created playlists while sorting my music

### ISSUE THREAD

**Issue by Ale5ander** [Shpigford/plylst#68]
Hello.

I've started to use Plylst few days ago and I'm in love in it's idea. Thank you so much for this app.
But I faced with a huge problem. I think playlists work wrong for me. Eg I created playlist with following rules: 
1. Energy is Insane, Danceability is Super.
2. Uses only songs I've liked.
3. Sorted randomly.

And that what's I got. This is definately not a dance track.
![2020-02-25_18-41-07](https://user-images.githubusercontent.com/36563103/75321706-68796380-5882-11ea-8bf3-8d761ba2a896.png)

Same story with playlist that should sort tracks which has not played in past 90 days (https://plylst.app/playlists/n6z7ghzq38). This playlist contain following rules:
1. Last Played Days Ago is greater than 90.
2. Uses only songs I've liked.
3. Sorted randomly.

Okay, 2nd and 3rd rules works fine. It's all my liked tracks but all of them has been played few days ago.

**Comment by Shpigford** [comment]
Thanks for reporting this @Ale5ander! I've pushed out fixes for both of these issues.

The first one with energy/danceability was just an issue with the data in those tooltips (the actual tracks matched properly). That's been fixed.

The Last Played Days Ago was incorrectly inverse, which has also been fixed.
