### ISSUE TITLE
New rule in Rule Builder: Most played songs

### ISSUE THREAD

**Issue by Ale5ander** [Shpigford/plylst#71]
Hello.

I tried to create smart playlist based on my most played tracks and only one rule that I found is: play count greater than.
Main problem of this rule is that you always need to edit count of plays. Much better to create special rule which will be include most played songs in amount of ... (set it too by yourself). Just set it up once and forget about edits.

**Comment by Shpigford** [comment]
You'd actually just use the "Sort" feature and set to "Most Played".

![most_played](https://user-images.githubusercontent.com/35243/75459676-c753e100-5945-11ea-9039-54fcff57a069.png)

**Comment by Ale5ander** [comment]
It just sorting your music inside playlist which already created and I'm talking about rule that will add music to current playlist.

**Comment by Shpigford** [comment]
You can create a playlist with no rules and only sort by Most Played and it should do what you want.
