### ISSUE TITLE
Play count-based rules work incorrectly

### ISSUE THREAD

**Issue by vokinpirks** [Shpigford/plylst#76]
Hello!
The first case:
I've created a playlist https://plylst.app/playlists/v63oqhe0v6
There must be tracks which I liked and played more than 1 time.
However, it says "No songs match your filters." I've been using plylist about a month or even more, so I'm sure there is a whole bunch of tracks which I've listened to 2+ times during this period.
Also, I have a Last.fm account connected to Spotify and it kinda proves my points. My stats for March (and that's even less than a month for now!): https://www.last.fm/user/NameNotFound42/library/tracks?from=2020-03-01&rangetype=1month&page=1.
So, it seems like something is definitely wrong with play counts.

The second case:
I've changed that playlist so it's based on the "Any songs from artists I've liked" option and I've got really weird results.
https://plylst.app/playlists/48yp7hpy28
The resulting playlist contains 1000 tracks of just three artists (Bonobo, Sigur Ros, The Shins) although I'm not subscribed to any of them. And, of course, I haven't listened to any of these tracks more than once since I've been using Plylst, I'm pretty sure about that. 
Moreover, tracks got duplicated there for some reason.
https://open.spotify.com/playlist/0Xqm5KLgCI2oeCww6FRWyE?si=c_AMLAB5S8yHAj6_1ipXIg
Sort by song title and you'll see.

**Comment by Shpigford** [comment]
Are you still having these issues? There was a bug that was preventing accounts from updating and am curious if this was related.

**Comment by vokinpirks** [comment]
> Are you still having these issues? 
Seems so.
