### ISSUE TITLE
new playlist error

### ISSUE THREAD

**Issue by geocodinglife** [Shpigford/plylst#78]
after new account is created a I click the button create new playlist
and this error appeared 

![flatten](https://user-images.githubusercontent.com/5788817/76689199-71e42900-6601-11ea-8f5f-c23dde67e4c0.png)

**Comment by geocodinglife** [comment]
I think the error is because my spotify account don't have any like song selected, if this is the case, a message should show "You need to add like songs to your list"

**Comment by Shpigford** [comment]
Should be fixed now. Would just be an issue on new local setups where there isn't any data at all in the database yet. That method now checks to make sure there's something available.
