### ISSUE TITLE
Ability to delete playlists

### ISSUE THREAD

**Issue by Shpigford** [Shpigford/plylst#8]
Basic functionality needs to be added for deleting a playlist you've created in PLYLST.

Unfortunately the playlists in Spotify can't be deleted (there's no API endpoint) but we do need to allow deleting a playlist in PLYLST in the event the user doesn't want them to keep being regenerated in their Spotify account.

**Comment by jamespember** [comment]
I'm on this one.

**Comment by jamespember** [comment]
https://github.com/Shpigford/plylst/pull/11
