### ISSUE TITLE
Playlists only work for the whole Spotify catalog

### ISSUE THREAD

**Issue by Rollomat** [Shpigford/plylst#84]
Hi, 

I love this tool, but I've got one big problem. When I want to create a new playlist and select the full Spotify catalog as a source, things work and I get playlists with songs. When I select “Only songs I’ve liked“ or “Any songs from artists I’ve liked“ as a source, I never get a match. Could you help me, please? Thank you very much in advance!

**Comment by Rollomat** [comment]
PS: The filter should not be the problem. Even if I want the playlist to include all the songs I've liked, no song is provided.

**Comment by SijanC147** [comment]
Sorry if i'm missing something but i'm not sure why this issue was closed, I am experiencing the same issue with "Only songs I've Liked" whereas "Full Spotify Catalog" works flawlessly. Any assistance would be appreciated, thanks 🙏
