### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by supercrisz** [Shpigford/plylst#87]
I have signed up and tried to make several playlists. But it shows "No songs match your filters" all the time. Also the playlists are not showing up in my Spotify account. Only if I make a playlist based on "full Spotify catalog" instead of "Only songs i liked", then I see songs. But also then, the playlist does not show up in my Spotify account

**update**
I know see the 'how to start'module. I am not known with github. I have downloaded GitHub desktop and also downloaded the repos. But I miss a full manual where to click to open command line.. I am know in a situation that i get an error when I try to do bin/setup after I added the config file with the client and secret key from Spotify. Is there a guide that gives the steps in more detail?

**Comment by Shpigford** [comment]
Hey there! Are you interested in installing it locally? That's not necessary to actually use PLYLST...it's mostly just if you want to do custom code on it.

If you aren't seeing any songs in your PLYLST account, that's a separate issue. If you can let me know your email address or Spotify user ID, I can look up your account and see what's going on.
