### ISSUE TITLE
Website not Loading songs when using Songs i like

### ISSUE THREAD

**Issue by confidentjohn** [Shpigford/plylst#95]
Hi
I just signed up today on the website app. I am having the same issue.

The stream section is blank.

If i create a playlist referencing Full Spotify Catalog, tracks get returned in a playlist.

However, for example i tried to make a playlist with this configuration

Name - Loved Radiohead
Auto Update - Yes
Privacy - Public
Source - Only Songs I have liked
Rules, Artist Name - Contains - Radiohead
This returns blank

I created some other playlists like, playcount is less than 2 for liked songs, which also returns empty (This is figure is correct behavior as i only just connected to the app, however as the stream isnt updating im not sure it will work)

Really look forward to using this app though. Thank you for creating.

**Comment by Shpigford** [comment]
We had some server issues, which have been resolved. Will take a bit of time for the background jobs to catch up, though. If this is still happening in 24 hours, let me know.
