### ISSUE TITLE
Spotify Playlist getting created, but Not getting any tracks from playlists

### ISSUE THREAD

**Issue by confidentjohn** [Shpigford/plylst#96]
Created a test playlist.

Name - fffff
Auto Update - Yes
Privacy - Public

Source - Full Spotify Catalog

https://plylst.app/playlists/655qhooj96

This returns items in the plylst website, however in spotify a blank playlist is created.

**Comment by Shpigford** [comment]
We had some server issues, which have been resolved. Will take a bit of time for the background jobs to catch up, though. If this is still happening in 24 hours, let me know.
